---
title: "Map STRUCTURE results for individuals"
author: "Justin Anderson"
date: "May 11, 2015"
output: html_document
---

This script is to map the STRUCTURE assignments for each individual on a geographic map.  

Installing Packages
```{r installing packsages, echo=FALSE, warning=FALSE,tidy=TRUE}
library(RgoogleMaps)
```


Load Supplemental Table 1 File (remove top line to leave column headers only)
```{r,echo=FALSE}
struc_map <- read.table(" <TABLE S1> ", header=TRUE)
```

Create Map and add points
```{r,echo=FALSE}

struc_map$col3=as.character(struc_map$Color)  #convert color column to characters corresponding to population

center = c((max(struc_map$latitude)+min(struc_map$latitude))/2,(max(struc_map$longitude)+min(struc_map$longitude))/2) # calculate the center of the map

x6 <- GetMap(center=center, zoom = 4,  maptype = "satellite",) # querry google maps for map centered on "center"
#zoom = 4 then crop for figure. zoom 5 was too close to show all images
#maptype = "satellite", can also be Roadmap, Hybrid, and others fround in RgoogleMaps library

PlotOnStaticMap(MyMap=x6, lon =jitter(struc_map$longitude,1,.5), lat= jitter(struc_map$latitude,1,.5), col= "black", bg= struc_map$col3,pch=21, FUN=points) #plot on map
#jitter aadded to view all samples due to multiple lines coming from a single geographic location. New runs will move points to new jittered location. 
#pch=21 for open circles
#col = "black" equals circles with black edges
#bg=struc_map$col3 colors the inner circles according to population structure analysis
```

